export const CARD_SUCCESS = 'CARD_SUCCESS';
export const CARD_FAIL = 'CARD_FAIL';
export const PROGRESS_INCREMENT = 'PROGRESS_INCREMENT';
export const RESULT_SUCCESS = 'RESULT_SUCCESS';
export const RESULT_FAIL = 'RESULT_FAIL';